ERROR - 2023-03-21 15:19:09 --> mysqli_sql_exception: Unknown table 'bd_taller.cargos' in C:\xampp\htdocs\miproyecto1\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\miproyecto1\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT `cargos`...', 0)
#1 C:\xampp\htdocs\miproyecto1\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `cargos`...')
#2 C:\xampp\htdocs\miproyecto1\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `cargos`...')
#3 C:\xampp\htdocs\miproyecto1\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `cargos`...', Array, false)
#4 C:\xampp\htdocs\miproyecto1\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\miproyecto1\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\miproyecto1\app\Models\DepartamentosModel.php(37): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\miproyecto1\app\Controllers\Departamentos.php(62): App\Models\DepartamentosModel->traer_Dpto('1')
#8 C:\xampp\htdocs\miproyecto1\system\CodeIgniter.php(934): App\Controllers\Departamentos->buscar_dpto('1')
#9 C:\xampp\htdocs\miproyecto1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departamentos))
#10 C:\xampp\htdocs\miproyecto1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\miproyecto1\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-21 15:19:09 --> Unknown table 'bd_taller.cargos'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `cargos`.*
FROM `departamentos`
WHERE `id` = :id:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 4 APPPATH\Models\DepartamentosModel.php(37): CodeIgniter\BaseModel->first()
 5 APPPATH\Controllers\Departamentos.php(62): App\Models\DepartamentosModel->traer_Dpto('1')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Departamentos->buscar_dpto('1')
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departamentos))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-21 16:36:44 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`bd_taller`.`municipios`, CONSTRAINT `municipios_ibfk_1` FOREIGN KEY (`id_dpto`) REFERENCES `departamentos` (`id`)) in C:\xampp\htdocs\miproyecto1\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\miproyecto1\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `mu...', 0)
#1 C:\xampp\htdocs\miproyecto1\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `mu...')
#2 C:\xampp\htdocs\miproyecto1\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `mu...')
#3 C:\xampp\htdocs\miproyecto1\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `mu...', Array, false)
#4 C:\xampp\htdocs\miproyecto1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\miproyecto1\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\miproyecto1\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\miproyecto1\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\miproyecto1\app\Controllers\Municipios.php(45): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\miproyecto1\system\CodeIgniter.php(934): App\Controllers\Municipios->insertar()
#10 C:\xampp\htdocs\miproyecto1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Municipios))
#11 C:\xampp\htdocs\miproyecto1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\miproyecto1\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-03-21 16:36:44 --> Cannot add or update a child row: a foreign key constraint fails (`bd_taller`.`municipios`, CONSTRAINT `municipios_ibfk_1` FOREIGN KEY (`id_dpto`) REFERENCES `departamentos` (`id`))
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `municipios` (`id_dpto`, `nombre`) VALUES (:id_dpto:, :nombre:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Municipios.php(45): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Municipios->insertar()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Municipios))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
